# Generated by Django 4.0.8 on 2023-01-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
