# Generated by Django 4.0.8 on 2023-01-16 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0002_alter_vote_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='down_vote_by',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='up_vote_by',
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('up_vote', 'up_vote'), ('down_vote', 'down_vote')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.post'),
        ),
    ]
